version: "3.9"

services:

  kind:
    image: kindest/node:v1.29.0
    container_name: kind-control-plane
    privileged: true
    volumes:
      - kind-data:/var/lib/docker
      - ./kind/cluster.yaml:/kind/cluster.yaml
      - ./k8s:/k8s
      - ./helm:/helm
      - ./db:/db
      - ./app:/app
    command: >
      sh -c "
      kind create cluster --name vault-demo --config /kind/cluster.yaml &&
      export KUBECONFIG=/root/.kube/config &&
      kubectl apply -f /k8s/namespace.yaml &&
      kubectl apply -f /k8s/serviceaccounts.yaml &&
      kubectl apply -f /k8s/rbac.yaml &&
      helm repo add hashicorp https://helm.releases.hashicorp.com &&
      helm repo update &&
      helm install vault hashicorp/vault -n vault -f /helm/vault/values.yaml &&
      echo 'Waiting for Vault Pods...' &&
      kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=vault -n vault --timeout=180s &&
      echo 'Starting Vault Port Forward...' &&
      nohup kubectl port-forward svc/vault 8200:8200 -n vault > /dev/null 2>&1 &
      sleep 10 &&
      kubectl apply -f /db/postgres-deployment.yaml &&
      kubectl apply -f /app/app-deployment.yaml &&
      sleep infinity
      "
    ports:
      - "8200:8200"

  vault-setup:
    build:
      context: ./vault
      dockerfile: Dockerfile
    depends_on:
      - kind
    volumes:
      - ./vault:/vault
    environment:
      VAULT_ADDR: http://kind-control-plane:30200
      VAULT_ROOT_TOKEN: root
    entrypoint:
      - sh
      - -c
      - |
        echo "Waiting for Vault..."
        until curl -s -f http://kind:8200/v1/sys/health > /dev/null; do
          printf '.' && sleep 3;
        done
        echo "Vault is ready!"
        chmod +x /vault/setup.sh
        /vault/setup.sh
        sleep infinity

volumes:
  kind-data: