apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-kv-reader-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-db-user-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-token-reviewer
  namespace: vault
